version: '3.4'

services:
  azuretypescripte2eapps:
    image: azuretypescripte2eapps
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
